// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/administration/configurations-financieres": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "administration"
                ],
                "summary": "Configurations financières actives (admin)",
                "responses": {}
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "administration"
                ],
                "summary": "Modifier une configuration financière (admin) — historisé",
                "responses": {}
            }
        },
        "/administration/journaux-audit": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "administration"
                ],
                "summary": "Journal d'audit (admin, lecture seule) — paginé, 10 par page, plus récents d'abord",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page (défaut 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Éléments par page (1..100, défaut 10)",
                        "name": "taille",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtre exact sur l'action (ex. litige:decision)",
                        "name": "action",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Page-administration_JournalAudit"
                        }
                    }
                }
            }
        },
        "/administration/statistiques": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "administration"
                ],
                "summary": "KPIs du tableau de bord admin (cache Redis 60 s)",
                "responses": {}
            }
        },
        "/auth/admin/connexion": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Connexion administrateur",
                "responses": {}
            }
        },
        "/auth/changer-mot-de-passe": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Changer son mot de passe",
                "responses": {}
            }
        },
        "/auth/connexion": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Connexion joueur",
                "responses": {}
            }
        },
        "/auth/deconnexion": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Déconnexion (invalide la session Redis)",
                "responses": {}
            }
        },
        "/auth/inscription": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Créer un compte joueur",
                "parameters": [
                    {
                        "description": "Compte à créer",
                        "name": "corps",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.EntreeInscription"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/auth/moi": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Utilisateur ou administrateur courant",
                "responses": {}
            }
        },
        "/auth/mot-de-passe-oublie": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Demande de réinitialisation de mot de passe",
                "responses": {}
            }
        },
        "/auth/reinitialisation-mot-de-passe": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Réinitialiser le mot de passe avec un token",
                "responses": {}
            }
        },
        "/comptes-gamers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "comptes-gamers"
                ],
                "summary": "Mes identifiants de joueur par jeu/plateforme",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/comptes_gamers.CompteGamer"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "comptes-gamers"
                ],
                "summary": "Ajouter un identifiant de joueur (jeu + plateforme)",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/comptes_gamers.CompteGamer"
                        }
                    }
                }
            }
        },
        "/comptes-gamers/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "comptes-gamers"
                ],
                "summary": "Supprimer un identifiant de joueur (propriétaire)",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "comptes-gamers"
                ],
                "summary": "Modifier un identifiant de joueur (propriétaire)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/comptes_gamers.CompteGamer"
                        }
                    }
                }
            }
        },
        "/configurations-financieres": {
            "get": {
                "tags": [
                    "administration"
                ],
                "summary": "Règles financières actives (public) — commission, mises min/max, frais de retrait",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/administration.ConfigurationPublique"
                            }
                        }
                    }
                }
            }
        },
        "/contact": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "contact"
                ],
                "summary": "Messages de contact paginés (admin) — ?page=1\u0026taille=10\u0026statut=nouveau|lu|traite, plus récents d'abord",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Page-contact_MessageContact"
                        }
                    },
                    "400": {
                        "description": "statut inconnu",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "contact"
                ],
                "summary": "Envoyer un message de contact (public ; jeton joueur facultatif → utilisateurId ; anti-spam 5 messages/heure/IP)",
                "parameters": [
                    {
                        "description": "nom (≥ 2), email, sujet (≥ 3), message (10 à 2000 caractères)",
                        "name": "corps",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contact.entreeMessage"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/contact.MessageContact"
                        }
                    },
                    "400": {
                        "description": "validation échouée (details par champ)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "429": {
                        "description": "Trop de messages envoyés, réessayez dans une heure.",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/contact/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "contact"
                ],
                "summary": "Détail d'un message de contact (admin)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contact.MessageContact"
                        }
                    },
                    "404": {
                        "description": "message introuvable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "contact"
                ],
                "summary": "Supprimer un message de contact (admin) — journalisé (contact:suppression)",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "message introuvable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "contact"
                ],
                "summary": "Traiter un message de contact (admin) : statut et/ou note interne — changement de statut journalisé (contact:statut_\u003cstatut\u003e)",
                "parameters": [
                    {
                        "description": "statut (nouveau|lu|traite) et/ou noteAdmin (≤ 2000 caractères)",
                        "name": "corps",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contact.entreeTraitement"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contact.MessageContact"
                        }
                    },
                    "400": {
                        "description": "validation échouée",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "message introuvable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/defis": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "defis"
                ],
                "summary": "Défis ouverts (?jeu=, ?plateforme=, ?miseMax=) — ou mes défis, tous statuts (?mes=1)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/defis.DefiListe"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "defis"
                ],
                "summary": "Créer un défi (bloque la mise du créateur)",
                "responses": {}
            }
        },
        "/defis/ouverts": {
            "get": {
                "tags": [
                    "defis"
                ],
                "summary": "Défis ouverts, en attente d'un adversaire (public — site vitrine)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/defis.DefiListe"
                            }
                        }
                    }
                }
            }
        },
        "/defis/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "defis"
                ],
                "summary": "Détail d'un défi (libellés créateur/jeu/plateforme) et son match s'il existe",
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "defis"
                ],
                "summary": "Annuler un défi ouvert (rend la mise au créateur, moins la commission)",
                "responses": {}
            }
        },
        "/defis/{id}/rejoindre": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "defis"
                ],
                "summary": "Rejoindre un défi (bloque la mise, crée le match)",
                "responses": {}
            }
        },
        "/jeux": {
            "get": {
                "tags": [
                    "jeux"
                ],
                "summary": "Catalogue des jeux (public : actifs ; admin : tous) — ?categorie= pour filtrer",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/jeux.Jeu"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "jeux"
                ],
                "summary": "Ajouter un jeu (admin) — catégorie obligatoire",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/jeux.Jeu"
                        }
                    }
                }
            }
        },
        "/jeux/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "jeux"
                ],
                "summary": "Supprimer un jeu (admin)",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "jeux"
                ],
                "summary": "Modifier un jeu (admin) : nom, catégorie, statut",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/jeux.Jeu"
                        }
                    }
                }
            }
        },
        "/litiges": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "litiges"
                ],
                "summary": "Mes litiges (admin : ?tous=1 pour tous)",
                "responses": {}
            }
        },
        "/litiges/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "litiges"
                ],
                "summary": "Décision arbitrale (admin) — règlement au gagnant ou remboursement croisé (chaque mise rendue moins la commission)",
                "responses": {}
            }
        },
        "/matchs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "matchs"
                ],
                "summary": "Mes matchs (tableau, ?statut=en_cours|preuve_requise|nul_en_attente|litige|termine) ; admin ?tous=1 : page utils.Page[MatchEnrichi] (10/page, ?page\u0026taille)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "en_cours | preuve_requise | nul_en_attente | litige | termine (verification : lignes historiques)",
                        "name": "statut",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Admin : 1 = tous les matchs, réponse paginée",
                        "name": "tous",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Admin (?tous=1) : page, défaut 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Admin (?tous=1) : éléments par page, 1..100, défaut 10",
                        "name": "taille",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/matchs.MatchEnrichi"
                            }
                        }
                    }
                }
            }
        },
        "/matchs/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "matchs"
                ],
                "summary": "Détail d'un match (libellés joueurs/jeu/plateforme + déclarations + choix de nul)",
                "responses": {}
            }
        },
        "/matchs/{id}/choix-nul": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "matchs"
                ],
                "summary": "Après un nul déclaré des deux côtés : rejouer (si les DEUX l'acceptent, aucun mouvement d'argent) ou partager (chacun mise × (1 − commission))",
                "responses": {}
            }
        },
        "/matchs/{id}/confirmation": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "matchs"
                ],
                "summary": "Confirmer le score proposé par l'adversaire — le serveur inscrit la déclaration miroir (aucun chiffre envoyé par le client) et règle le match",
                "responses": {}
            }
        },
        "/matchs/{id}/declaration": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "matchs"
                ],
                "summary": "Déclarer le score d'un match (première déclaration : chrono de confirmation ; seconde : règlement immédiat, nul ou désaccord)",
                "responses": {}
            }
        },
        "/matchs/{id}/litige": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "litiges"
                ],
                "summary": "Ouvrir un litige sur un match",
                "responses": {}
            }
        },
        "/matchs/{id}/preuves": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "preuves"
                ],
                "summary": "Preuves d'un match",
                "responses": {}
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "preuves"
                ],
                "summary": "Envoyer une preuve de match (multipart → disque local)",
                "responses": {}
            }
        },
        "/matchs/{id}/validation": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "matchs"
                ],
                "summary": "Valider un match (admin) — règlement de l'escrow d'une ligne en vérification ou d'un match en litige dont le gagnant est désigné",
                "responses": {}
            }
        },
        "/notifications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Mes notifications",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/notifications.Notification"
                            }
                        }
                    }
                }
            }
        },
        "/notifications/jeton-fcm": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Enregistrer le jeton FCM de l'appareil courant (push)",
                "responses": {}
            }
        },
        "/notifications/{id}/lue": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Marquer une notification comme lue",
                "responses": {}
            }
        },
        "/paiements": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "paiements"
                ],
                "summary": "Suivi des paiements (admin) — paginé, 10 par page, plus récents d'abord",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page (défaut 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Éléments par page (1..100, défaut 10)",
                        "name": "taille",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "depot | retrait",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "en_attente | reussi | echoue | rembourse",
                        "name": "statut",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Page-paiements_Paiement"
                        }
                    }
                }
            }
        },
        "/paiements/callback-fusion": {
            "post": {
                "tags": [
                    "paiements"
                ],
                "summary": "Webhook MoneyFusion (public)",
                "responses": {}
            }
        },
        "/paiements/callback-ligdicash": {
            "post": {
                "tags": [
                    "paiements"
                ],
                "summary": "Webhook LigdiCash (public)",
                "responses": {}
            }
        },
        "/paiements/depot": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "paiements"
                ],
                "summary": "Dépôt via LigdiCash/MoneyFusion",
                "responses": {}
            }
        },
        "/paiements/retrait": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "paiements"
                ],
                "summary": "Retrait vers Mobile Money",
                "responses": {}
            }
        },
        "/paiements/{id}/statut": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "paiements"
                ],
                "summary": "Validation/échec/remboursement manuel (admin)",
                "responses": {}
            }
        },
        "/plateformes": {
            "get": {
                "tags": [
                    "plateformes"
                ],
                "summary": "Catalogue des plateformes (public : actives ; admin : toutes) — ?famille= pour filtrer",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/plateformes.Plateforme"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "plateformes"
                ],
                "summary": "Ajouter une plateforme (admin) — famille obligatoire (pc, console, mobile)",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/plateformes.Plateforme"
                        }
                    }
                }
            }
        },
        "/plateformes/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "plateformes"
                ],
                "summary": "Supprimer une plateforme (admin)",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "plateformes"
                ],
                "summary": "Modifier une plateforme (admin) : nom, famille, statut",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/plateformes.Plateforme"
                        }
                    }
                }
            }
        },
        "/portefeuille": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "portefeuille"
                ],
                "summary": "Solde du portefeuille",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/portefeuilles.Portefeuille"
                        }
                    }
                }
            }
        },
        "/portefeuille/transactions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "portefeuille"
                ],
                "summary": "Historique des mouvements",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/portefeuilles.TransactionPortefeuille"
                            }
                        }
                    }
                }
            }
        },
        "/preuves/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "preuves"
                ],
                "summary": "Valider/rejeter une preuve (admin)",
                "responses": {}
            }
        },
        "/preuves/{id}/fichier": {
            "get": {
                "responses": {}
            }
        },
        "/sante": {
            "get": {
                "tags": [
                    "systeme"
                ],
                "summary": "Vérification de disponibilité (Postgres + Redis)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/temps-reel": {
            "get": {
                "description": "Ouvre le socket unique de la plateforme : ` + "`" + `GET /api/temps-reel?ticket=\u003cticket\u003e` + "`" + ` (schéma ` + "`" + `ws://` + "`" + ` ou ` + "`" + `wss://` + "`" + `). Le ticket vient de ` + "`" + `POST /api/temps-reel/ticket` + "`" + ` ; sans ticket — ou avec un ticket expiré, déjà consommé ou invalide, auquel cas un événement ` + "`" + `connexion.refusee` + "`" + ` est envoyé d'abord — la connexion est acceptée en **visiteur** et limitée aux salons publics. Le serveur envoie ensuite ` + "`" + `connexion.prete` + "`" + `. Actions client (JSON) : ` + "`" + `{\"action\":\"abonner\",\"salons\":[…]}` + "`" + `, ` + "`" + `{\"action\":\"desabonner\",\"salons\":[…]}` + "`" + `, ` + "`" + `{\"action\":\"presence\",\"salon\":\"match:\u003cid\u003e\",\"surLaPage\":true}` + "`" + `, ` + "`" + `{\"action\":\"ping\"}` + "`" + `. Battement de cœur : ping serveur toutes les 30 s, fermeture après 60 s sans signe de vie.",
                "tags": [
                    "temps-reel"
                ],
                "summary": "Socket temps réel (multiplexé par salons)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ticket à usage unique obtenu via POST /api/temps-reel/ticket",
                        "name": "ticket",
                        "in": "query"
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "origine non autorisée",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "426": {
                        "description": "connexion WebSocket requise",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/temps-reel/ticket": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Échange la session Bearer contre un ticket à usage unique (32 octets aléatoires, base64 URL, TTL 60 s). Le navigateur ouvre ensuite ` + "`" + `wss://\u003chôte\u003e/api/temps-reel?ticket=\u003cticket\u003e` + "`" + ` : le jeton JWT ne transite jamais dans l'URL. Un ticket absent, expiré ou déjà consommé n'échoue pas la connexion — le socket s'ouvre en visiteur (salons publics) après un événement ` + "`" + `connexion.refusee` + "`" + `.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "temps-reel"
                ],
                "summary": "Ticket d'ouverture du socket temps réel",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tempsreel.ReponseTicket"
                        }
                    },
                    "401": {
                        "description": "authentification requise",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "service temps réel indisponible",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/utilisateurs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "utilisateurs"
                ],
                "summary": "Liste des comptes (admin) — paginée, 10 par page, plus récents d'abord",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page (défaut 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Éléments par page (1..100, défaut 10)",
                        "name": "taille",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pseudo ou e-mail (recherche partielle)",
                        "name": "recherche",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "actif | suspendu | en_attente | supprime",
                        "name": "statut",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Page-auth_Utilisateur"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "utilisateurs"
                ],
                "summary": "Créer un compte joueur (admin) — mêmes règles que l'inscription, portefeuille créé, aucune session",
                "parameters": [
                    {
                        "description": "Compte à créer",
                        "name": "corps",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utilisateurs.EntreeCreation"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth.Utilisateur"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/utilisateurs/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "utilisateurs"
                ],
                "summary": "Détail d'un compte (admin) : utilisateur + portefeuille { soldeDisponible, soldeBloque }",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utilisateurs.UtilisateurDetail"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "utilisateurs"
                ],
                "summary": "Suppression logique d'un compte (admin) — refusée (409) si de l'argent ou un match est en jeu",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "utilisateurs"
                ],
                "summary": "Mettre à jour un compte (propriétaire : profil ; admin : tout, dont email, statut, motDePasse)",
                "parameters": [
                    {
                        "description": "Champs à modifier (tous facultatifs)",
                        "name": "corps",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utilisateurs.EntreeModification"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.Utilisateur"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/utilisateurs/{id}/statut": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "utilisateurs"
                ],
                "summary": "Activer / suspendre un compte (admin)",
                "responses": {}
            }
        }
    },
    "definitions": {
        "administration.ConfigurationPublique": {
            "type": "object",
            "properties": {
                "devise": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "valeur": {
                    "type": "number"
                }
            }
        },
        "administration.JournalAudit": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "administrateurId": {
                    "type": "string"
                },
                "adresseIp": {
                    "type": "string"
                },
                "ancienneValeur": {
                    "type": "string"
                },
                "dateCreation": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "identifiantCible": {
                    "type": "string"
                },
                "nouvelleValeur": {
                    "type": "string"
                },
                "tableCible": {
                    "type": "string"
                },
                "utilisateurId": {
                    "type": "string"
                }
            }
        },
        "auth.EntreeInscription": {
            "type": "object",
            "required": [
                "email",
                "motDePasse",
                "nomUtilisateur"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "motDePasse": {
                    "type": "string",
                    "minLength": 6
                },
                "nomUtilisateur": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                },
                "pays": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                }
            }
        },
        "auth.Utilisateur": {
            "type": "object",
            "properties": {
                "dateCreation": {
                    "type": "string"
                },
                "dateModification": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nomUtilisateur": {
                    "type": "string"
                },
                "pays": {
                    "type": "string"
                },
                "photoProfil": {
                    "type": "string"
                },
                "statut": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                }
            }
        },
        "comptes_gamers.CompteGamer": {
            "type": "object",
            "properties": {
                "dateCreation": {
                    "type": "string"
                },
                "dateModification": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "identifiantJoueur": {
                    "type": "string"
                },
                "jeuId": {
                    "type": "string"
                },
                "nomAffichage": {
                    "type": "string"
                },
                "plateformeId": {
                    "type": "string"
                },
                "utilisateurId": {
                    "type": "string"
                }
            }
        },
        "contact.MessageContact": {
            "type": "object",
            "properties": {
                "dateCreation": {
                    "type": "string"
                },
                "dateModification": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "nom": {
                    "type": "string"
                },
                "noteAdmin": {
                    "type": "string"
                },
                "statut": {
                    "type": "string"
                },
                "sujet": {
                    "type": "string"
                },
                "utilisateurId": {
                    "type": "string"
                }
            }
        },
        "contact.entreeMessage": {
            "type": "object",
            "required": [
                "email",
                "message",
                "nom",
                "sujet"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 255
                },
                "message": {
                    "type": "string",
                    "maxLength": 2000,
                    "minLength": 10
                },
                "nom": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "sujet": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 3
                }
            }
        },
        "contact.entreeTraitement": {
            "type": "object",
            "properties": {
                "noteAdmin": {
                    "type": "string",
                    "maxLength": 2000
                },
                "statut": {
                    "type": "string",
                    "enum": [
                        "nouveau",
                        "lu",
                        "traite"
                    ]
                }
            }
        },
        "defis.DefiListe": {
            "type": "object",
            "properties": {
                "createurId": {
                    "type": "string"
                },
                "createurNom": {
                    "type": "string"
                },
                "dateCreation": {
                    "type": "string"
                },
                "dateExpiration": {
                    "type": "string"
                },
                "dateModification": {
                    "type": "string"
                },
                "devise": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "jeuCategorie": {
                    "type": "string"
                },
                "jeuId": {
                    "type": "string"
                },
                "jeuNom": {
                    "type": "string"
                },
                "montantMise": {
                    "type": "number"
                },
                "plateformeFamille": {
                    "type": "string"
                },
                "plateformeId": {
                    "type": "string"
                },
                "plateformeNom": {
                    "type": "string"
                },
                "regles": {
                    "type": "string"
                },
                "statut": {
                    "type": "string"
                }
            }
        },
        "jeux.Jeu": {
            "type": "object",
            "properties": {
                "categorie": {
                    "type": "string"
                },
                "dateCreation": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nom": {
                    "type": "string"
                },
                "statut": {
                    "type": "string"
                }
            }
        },
        "matchs.MatchEnrichi": {
            "type": "object",
            "properties": {
                "dateCreation": {
                    "type": "string"
                },
                "dateDebut": {
                    "type": "string"
                },
                "dateFin": {
                    "type": "string"
                },
                "defiId": {
                    "type": "string"
                },
                "devise": {
                    "type": "string"
                },
                "echeance": {
                    "description": "Echeance / EcheanceType portent le chrono en cours (confirmation, preuve, choix_nul).\nLe client les lit au chargement de la page et les égrène sans appel réseau ; le\nserveur les republie en direct via match.chrono.",
                    "type": "string"
                },
                "echeanceType": {
                    "type": "string"
                },
                "gagnantId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "jeuNom": {
                    "type": "string"
                },
                "joueur1Id": {
                    "description": "Noms de colonnes explicites : GORM dériverait ` + "`" + `joueur1_id` + "`" + ` / ` + "`" + `score_joueur1` + "`" + `,\nalors que le modèle de données (§7, table 6) impose ` + "`" + `joueur_1_id` + "`" + ` / ` + "`" + `score_joueur_1` + "`" + `,\nnoms utilisés par les requêtes SQL brutes (litiges, scores).",
                    "type": "string"
                },
                "joueur1Nom": {
                    "type": "string"
                },
                "joueur2Id": {
                    "type": "string"
                },
                "joueur2Nom": {
                    "type": "string"
                },
                "manche": {
                    "description": "Manche compte les rejeux d'un nul partagé : chaque « rejouer » accepté par les deux\njoueurs incrémente la manche SANS aucun mouvement d'argent (l'escrow reste bloqué).\nLes déclarations et les choix de nul sont datés par manche.",
                    "type": "integer"
                },
                "montantMise": {
                    "type": "number"
                },
                "perdantId": {
                    "type": "string"
                },
                "plateformeNom": {
                    "type": "string"
                },
                "scoreJoueur1": {
                    "type": "integer"
                },
                "scoreJoueur2": {
                    "type": "integer"
                },
                "statut": {
                    "type": "string"
                }
            }
        },
        "notifications.Notification": {
            "type": "object",
            "properties": {
                "dateCreation": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lu": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "titre": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "utilisateurId": {
                    "type": "string"
                }
            }
        },
        "paiements.Paiement": {
            "type": "object",
            "properties": {
                "dateCreation": {
                    "type": "string"
                },
                "dateModification": {
                    "type": "string"
                },
                "devise": {
                    "type": "string"
                },
                "frais": {
                    "description": "frais de retrait (configurations_financieres.frais_retrait)",
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "montant": {
                    "type": "number"
                },
                "operateur": {
                    "type": "string"
                },
                "prestataire": {
                    "type": "string"
                },
                "reference": {
                    "type": "string"
                },
                "referencePrestataire": {
                    "type": "string"
                },
                "statut": {
                    "type": "string"
                },
                "traite": {
                    "type": "boolean"
                },
                "type": {
                    "type": "string"
                },
                "utilisateurId": {
                    "type": "string"
                }
            }
        },
        "plateformes.Plateforme": {
            "type": "object",
            "properties": {
                "dateCreation": {
                    "type": "string"
                },
                "famille": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nom": {
                    "type": "string"
                },
                "statut": {
                    "type": "string"
                }
            }
        },
        "portefeuilles.Portefeuille": {
            "type": "object",
            "properties": {
                "dateCreation": {
                    "type": "string"
                },
                "dateModification": {
                    "type": "string"
                },
                "devise": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "soldeBloque": {
                    "type": "number"
                },
                "soldeDisponible": {
                    "type": "number"
                },
                "utilisateurId": {
                    "type": "string"
                }
            }
        },
        "portefeuilles.TransactionPortefeuille": {
            "type": "object",
            "properties": {
                "dateCreation": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "matchId": {
                    "type": "string"
                },
                "miseId": {
                    "type": "string"
                },
                "montant": {
                    "type": "number"
                },
                "portefeuilleId": {
                    "type": "string"
                },
                "reference": {
                    "type": "string"
                },
                "statut": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "tempsreel.ReponseTicket": {
            "type": "object",
            "properties": {
                "expiration": {
                    "type": "string"
                },
                "ticket": {
                    "type": "string"
                }
            }
        },
        "utilisateurs.EntreeCreation": {
            "type": "object",
            "required": [
                "email",
                "motDePasse",
                "nomUtilisateur"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "motDePasse": {
                    "type": "string",
                    "minLength": 6
                },
                "nomUtilisateur": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                },
                "pays": {
                    "type": "string"
                },
                "statut": {
                    "type": "string",
                    "enum": [
                        "actif",
                        "suspendu",
                        "en_attente"
                    ]
                },
                "telephone": {
                    "type": "string"
                }
            }
        },
        "utilisateurs.EntreeModification": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "motDePasse": {
                    "type": "string",
                    "minLength": 6
                },
                "nomUtilisateur": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                },
                "pays": {
                    "type": "string"
                },
                "photoProfil": {
                    "type": "string"
                },
                "statut": {
                    "type": "string",
                    "enum": [
                        "actif",
                        "suspendu",
                        "en_attente"
                    ]
                },
                "telephone": {
                    "type": "string"
                }
            }
        },
        "utilisateurs.PortefeuilleResume": {
            "type": "object",
            "properties": {
                "soldeBloque": {
                    "type": "number"
                },
                "soldeDisponible": {
                    "type": "number"
                }
            }
        },
        "utilisateurs.UtilisateurDetail": {
            "type": "object",
            "properties": {
                "dateCreation": {
                    "type": "string"
                },
                "dateModification": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nomUtilisateur": {
                    "type": "string"
                },
                "pays": {
                    "type": "string"
                },
                "photoProfil": {
                    "type": "string"
                },
                "portefeuille": {
                    "$ref": "#/definitions/utilisateurs.PortefeuilleResume"
                },
                "statut": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                }
            }
        },
        "utils.Page-administration_JournalAudit": {
            "type": "object",
            "properties": {
                "elements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/administration.JournalAudit"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "pages": {
                    "type": "integer"
                },
                "taille": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "utils.Page-auth_Utilisateur": {
            "type": "object",
            "properties": {
                "elements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/auth.Utilisateur"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "pages": {
                    "type": "integer"
                },
                "taille": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "utils.Page-contact_MessageContact": {
            "type": "object",
            "properties": {
                "elements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/contact.MessageContact"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "pages": {
                    "type": "integer"
                },
                "taille": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "utils.Page-paiements_Paiement": {
            "type": "object",
            "properties": {
                "elements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/paiements.Paiement"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "pages": {
                    "type": "integer"
                },
                "taille": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "QUI PERD API",
	Description:      "API de la plateforme QUI PERD (défis de match, escrow, paiements Mobile Money).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
