/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as JoueurRouteImport } from './routes/joueur'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAideRouteImport } from './routes/_public/aide'
import { Route as PublicCguRouteImport } from './routes/_public/cgu'
import { Route as PublicCommentCaMarcheRouteImport } from './routes/_public/comment-ca-marche'
import { Route as PublicConfidentialiteRouteImport } from './routes/_public/confidentialite'
import { Route as PublicConnexionRouteImport } from './routes/_public/connexion'
import { Route as PublicDefisRouteImport } from './routes/_public/defis'
import { Route as PublicInscriptionRouteImport } from './routes/_public/inscription'
import { Route as PublicJeuxRouteImport } from './routes/_public/jeux'
import { Route as PublicMentionsLegalesRouteImport } from './routes/_public/mentions-legales'
import { Route as PublicMotDePasseOublieRouteImport } from './routes/_public/mot-de-passe-oublie'
import { Route as PublicReinitialisationMotDePasseRouteImport } from './routes/_public/reinitialisation-mot-de-passe'
import { Route as AdminPriveRouteImport } from './routes/admin/_prive'
import { Route as AdminConnexionRouteImport } from './routes/admin/connexion'
import { Route as JoueurLitigesRouteImport } from './routes/joueur/litiges'
import { Route as JoueurNotificationsRouteImport } from './routes/joueur/notifications'
import { Route as JoueurPortefeuilleRouteImport } from './routes/joueur/portefeuille'
import { Route as JoueurProfilRouteImport } from './routes/joueur/profil'
import { Route as JoueurTableauDeBordRouteImport } from './routes/joueur/tableau-de-bord'
import { Route as AdminPriveConfigurationsRouteImport } from './routes/admin/_prive/configurations'
import { Route as AdminPriveJeuxPlateformesRouteImport } from './routes/admin/_prive/jeux-plateformes'
import { Route as AdminPriveJournalAuditRouteImport } from './routes/admin/_prive/journal-audit'
import { Route as AdminPriveMessagesRouteImport } from './routes/admin/_prive/messages'
import { Route as AdminPrivePaiementsRouteImport } from './routes/admin/_prive/paiements'
import { Route as AdminPriveTableauDeBordRouteImport } from './routes/admin/_prive/tableau-de-bord'
import { Route as AdminPriveUtilisateursRouteImport } from './routes/admin/_prive/utilisateurs'
import { Route as JoueurDefisIndexRouteImport } from './routes/joueur/defis/index'
import { Route as JoueurDefisDefiIdRouteImport } from './routes/joueur/defis/$defiId'
import { Route as JoueurDefisNouveauRouteImport } from './routes/joueur/defis/nouveau'
import { Route as JoueurMatchsIndexRouteImport } from './routes/joueur/matchs/index'
import { Route as JoueurMatchsMatchIdRouteImport } from './routes/joueur/matchs/$matchId'
import { Route as AdminPriveLitigesIndexRouteImport } from './routes/admin/_prive/litiges/index'
import { Route as AdminPriveLitigesLitigeIdRouteImport } from './routes/admin/_prive/litiges/$litigeId'
import { Route as AdminPriveMatchsIndexRouteImport } from './routes/admin/_prive/matchs/index'
import { Route as AdminPriveMatchsMatchIdRouteImport } from './routes/admin/_prive/matchs/$matchId'
import { Route as ApiMatchsMatchIdPreuvesRouteImport } from './routes/api/matchs/$matchId/preuves'
import { Route as ApiPreuvesPreuveIdFichierRouteImport } from './routes/api/preuves/$preuveId/fichier'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const JoueurRoute = JoueurRouteImport.update({
  id: '/joueur',
  path: '/joueur',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAideRoute = PublicAideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCguRoute = PublicCguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCommentCaMarcheRoute = PublicCommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => PublicRoute,
} as any)
const PublicConfidentialiteRoute = PublicConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => PublicRoute,
} as any)
const PublicConnexionRoute = PublicConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDefisRoute = PublicDefisRouteImport.update({
  id: '/defis',
  path: '/defis',
  getParentRoute: () => PublicRoute,
} as any)
const PublicInscriptionRoute = PublicInscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => PublicRoute,
} as any)
const PublicJeuxRoute = PublicJeuxRouteImport.update({
  id: '/jeux',
  path: '/jeux',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMentionsLegalesRoute = PublicMentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMotDePasseOublieRoute = PublicMotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => PublicRoute,
} as any)
const PublicReinitialisationMotDePasseRoute =
  PublicReinitialisationMotDePasseRouteImport.update({
    id: '/reinitialisation-mot-de-passe',
    path: '/reinitialisation-mot-de-passe',
    getParentRoute: () => PublicRoute,
  } as any)
const AdminPriveRoute = AdminPriveRouteImport.update({
  id: '/admin/_prive',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConnexionRoute = AdminConnexionRouteImport.update({
  id: '/admin/connexion',
  path: '/admin/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const JoueurLitigesRoute = JoueurLitigesRouteImport.update({
  id: '/litiges',
  path: '/litiges',
  getParentRoute: () => JoueurRoute,
} as any)
const JoueurNotificationsRoute = JoueurNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => JoueurRoute,
} as any)
const JoueurPortefeuilleRoute = JoueurPortefeuilleRouteImport.update({
  id: '/portefeuille',
  path: '/portefeuille',
  getParentRoute: () => JoueurRoute,
} as any)
const JoueurProfilRoute = JoueurProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => JoueurRoute,
} as any)
const JoueurTableauDeBordRoute = JoueurTableauDeBordRouteImport.update({
  id: '/tableau-de-bord',
  path: '/tableau-de-bord',
  getParentRoute: () => JoueurRoute,
} as any)
const AdminPriveConfigurationsRoute =
  AdminPriveConfigurationsRouteImport.update({
    id: '/configurations',
    path: '/configurations',
    getParentRoute: () => AdminPriveRoute,
  } as any)
const AdminPriveJeuxPlateformesRoute =
  AdminPriveJeuxPlateformesRouteImport.update({
    id: '/jeux-plateformes',
    path: '/jeux-plateformes',
    getParentRoute: () => AdminPriveRoute,
  } as any)
const AdminPriveJournalAuditRoute = AdminPriveJournalAuditRouteImport.update({
  id: '/journal-audit',
  path: '/journal-audit',
  getParentRoute: () => AdminPriveRoute,
} as any)
const AdminPriveMessagesRoute = AdminPriveMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminPriveRoute,
} as any)
const AdminPrivePaiementsRoute = AdminPrivePaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => AdminPriveRoute,
} as any)
const AdminPriveTableauDeBordRoute = AdminPriveTableauDeBordRouteImport.update({
  id: '/tableau-de-bord',
  path: '/tableau-de-bord',
  getParentRoute: () => AdminPriveRoute,
} as any)
const AdminPriveUtilisateursRoute = AdminPriveUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => AdminPriveRoute,
} as any)
const JoueurDefisIndexRoute = JoueurDefisIndexRouteImport.update({
  id: '/defis/',
  path: '/defis/',
  getParentRoute: () => JoueurRoute,
} as any)
const JoueurDefisDefiIdRoute = JoueurDefisDefiIdRouteImport.update({
  id: '/defis/$defiId',
  path: '/defis/$defiId',
  getParentRoute: () => JoueurRoute,
} as any)
const JoueurDefisNouveauRoute = JoueurDefisNouveauRouteImport.update({
  id: '/defis/nouveau',
  path: '/defis/nouveau',
  getParentRoute: () => JoueurRoute,
} as any)
const JoueurMatchsIndexRoute = JoueurMatchsIndexRouteImport.update({
  id: '/matchs/',
  path: '/matchs/',
  getParentRoute: () => JoueurRoute,
} as any)
const JoueurMatchsMatchIdRoute = JoueurMatchsMatchIdRouteImport.update({
  id: '/matchs/$matchId',
  path: '/matchs/$matchId',
  getParentRoute: () => JoueurRoute,
} as any)
const AdminPriveLitigesIndexRoute = AdminPriveLitigesIndexRouteImport.update({
  id: '/litiges/',
  path: '/litiges/',
  getParentRoute: () => AdminPriveRoute,
} as any)
const AdminPriveLitigesLitigeIdRoute =
  AdminPriveLitigesLitigeIdRouteImport.update({
    id: '/litiges/$litigeId',
    path: '/litiges/$litigeId',
    getParentRoute: () => AdminPriveRoute,
  } as any)
const AdminPriveMatchsIndexRoute = AdminPriveMatchsIndexRouteImport.update({
  id: '/matchs/',
  path: '/matchs/',
  getParentRoute: () => AdminPriveRoute,
} as any)
const AdminPriveMatchsMatchIdRoute = AdminPriveMatchsMatchIdRouteImport.update({
  id: '/matchs/$matchId',
  path: '/matchs/$matchId',
  getParentRoute: () => AdminPriveRoute,
} as any)
const ApiMatchsMatchIdPreuvesRoute = ApiMatchsMatchIdPreuvesRouteImport.update({
  id: '/api/matchs/$matchId/preuves',
  path: '/api/matchs/$matchId/preuves',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreuvesPreuveIdFichierRoute =
  ApiPreuvesPreuveIdFichierRouteImport.update({
    id: '/api/preuves/$preuveId/fichier',
    path: '/api/preuves/$preuveId/fichier',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/joueur': typeof JoueurRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/aide': typeof PublicAideRoute
  '/cgu': typeof PublicCguRoute
  '/comment-ca-marche': typeof PublicCommentCaMarcheRoute
  '/confidentialite': typeof PublicConfidentialiteRoute
  '/connexion': typeof PublicConnexionRoute
  '/defis': typeof PublicDefisRoute
  '/inscription': typeof PublicInscriptionRoute
  '/jeux': typeof PublicJeuxRoute
  '/mentions-legales': typeof PublicMentionsLegalesRoute
  '/mot-de-passe-oublie': typeof PublicMotDePasseOublieRoute
  '/reinitialisation-mot-de-passe': typeof PublicReinitialisationMotDePasseRoute
  '/admin': typeof AdminPriveRouteWithChildren
  '/admin/connexion': typeof AdminConnexionRoute
  '/joueur/litiges': typeof JoueurLitigesRoute
  '/joueur/notifications': typeof JoueurNotificationsRoute
  '/joueur/portefeuille': typeof JoueurPortefeuilleRoute
  '/joueur/profil': typeof JoueurProfilRoute
  '/joueur/tableau-de-bord': typeof JoueurTableauDeBordRoute
  '/admin/configurations': typeof AdminPriveConfigurationsRoute
  '/admin/jeux-plateformes': typeof AdminPriveJeuxPlateformesRoute
  '/admin/journal-audit': typeof AdminPriveJournalAuditRoute
  '/admin/messages': typeof AdminPriveMessagesRoute
  '/admin/paiements': typeof AdminPrivePaiementsRoute
  '/admin/tableau-de-bord': typeof AdminPriveTableauDeBordRoute
  '/admin/utilisateurs': typeof AdminPriveUtilisateursRoute
  '/joueur/defis/$defiId': typeof JoueurDefisDefiIdRoute
  '/joueur/defis/nouveau': typeof JoueurDefisNouveauRoute
  '/joueur/matchs/$matchId': typeof JoueurMatchsMatchIdRoute
  '/joueur/defis/': typeof JoueurDefisIndexRoute
  '/joueur/matchs/': typeof JoueurMatchsIndexRoute
  '/admin/litiges/$litigeId': typeof AdminPriveLitigesLitigeIdRoute
  '/admin/matchs/$matchId': typeof AdminPriveMatchsMatchIdRoute
  '/api/matchs/$matchId/preuves': typeof ApiMatchsMatchIdPreuvesRoute
  '/api/preuves/$preuveId/fichier': typeof ApiPreuvesPreuveIdFichierRoute
  '/admin/litiges/': typeof AdminPriveLitigesIndexRoute
  '/admin/matchs/': typeof AdminPriveMatchsIndexRoute
}
export interface FileRoutesByTo {
  '/joueur': typeof JoueurRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/aide': typeof PublicAideRoute
  '/cgu': typeof PublicCguRoute
  '/comment-ca-marche': typeof PublicCommentCaMarcheRoute
  '/confidentialite': typeof PublicConfidentialiteRoute
  '/connexion': typeof PublicConnexionRoute
  '/defis': typeof PublicDefisRoute
  '/inscription': typeof PublicInscriptionRoute
  '/jeux': typeof PublicJeuxRoute
  '/mentions-legales': typeof PublicMentionsLegalesRoute
  '/mot-de-passe-oublie': typeof PublicMotDePasseOublieRoute
  '/reinitialisation-mot-de-passe': typeof PublicReinitialisationMotDePasseRoute
  '/admin': typeof AdminPriveRouteWithChildren
  '/admin/connexion': typeof AdminConnexionRoute
  '/joueur/litiges': typeof JoueurLitigesRoute
  '/joueur/notifications': typeof JoueurNotificationsRoute
  '/joueur/portefeuille': typeof JoueurPortefeuilleRoute
  '/joueur/profil': typeof JoueurProfilRoute
  '/joueur/tableau-de-bord': typeof JoueurTableauDeBordRoute
  '/': typeof PublicIndexRoute
  '/admin/configurations': typeof AdminPriveConfigurationsRoute
  '/admin/jeux-plateformes': typeof AdminPriveJeuxPlateformesRoute
  '/admin/journal-audit': typeof AdminPriveJournalAuditRoute
  '/admin/messages': typeof AdminPriveMessagesRoute
  '/admin/paiements': typeof AdminPrivePaiementsRoute
  '/admin/tableau-de-bord': typeof AdminPriveTableauDeBordRoute
  '/admin/utilisateurs': typeof AdminPriveUtilisateursRoute
  '/joueur/defis/$defiId': typeof JoueurDefisDefiIdRoute
  '/joueur/defis/nouveau': typeof JoueurDefisNouveauRoute
  '/joueur/matchs/$matchId': typeof JoueurMatchsMatchIdRoute
  '/joueur/defis': typeof JoueurDefisIndexRoute
  '/joueur/matchs': typeof JoueurMatchsIndexRoute
  '/admin/litiges/$litigeId': typeof AdminPriveLitigesLitigeIdRoute
  '/admin/matchs/$matchId': typeof AdminPriveMatchsMatchIdRoute
  '/api/matchs/$matchId/preuves': typeof ApiMatchsMatchIdPreuvesRoute
  '/api/preuves/$preuveId/fichier': typeof ApiPreuvesPreuveIdFichierRoute
  '/admin/litiges': typeof AdminPriveLitigesIndexRoute
  '/admin/matchs': typeof AdminPriveMatchsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/joueur': typeof JoueurRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_public/aide': typeof PublicAideRoute
  '/_public/cgu': typeof PublicCguRoute
  '/_public/comment-ca-marche': typeof PublicCommentCaMarcheRoute
  '/_public/confidentialite': typeof PublicConfidentialiteRoute
  '/_public/connexion': typeof PublicConnexionRoute
  '/_public/defis': typeof PublicDefisRoute
  '/_public/inscription': typeof PublicInscriptionRoute
  '/_public/jeux': typeof PublicJeuxRoute
  '/_public/mentions-legales': typeof PublicMentionsLegalesRoute
  '/_public/mot-de-passe-oublie': typeof PublicMotDePasseOublieRoute
  '/_public/reinitialisation-mot-de-passe': typeof PublicReinitialisationMotDePasseRoute
  '/admin/_prive': typeof AdminPriveRouteWithChildren
  '/admin/connexion': typeof AdminConnexionRoute
  '/joueur/litiges': typeof JoueurLitigesRoute
  '/joueur/notifications': typeof JoueurNotificationsRoute
  '/joueur/portefeuille': typeof JoueurPortefeuilleRoute
  '/joueur/profil': typeof JoueurProfilRoute
  '/joueur/tableau-de-bord': typeof JoueurTableauDeBordRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/_prive/configurations': typeof AdminPriveConfigurationsRoute
  '/admin/_prive/jeux-plateformes': typeof AdminPriveJeuxPlateformesRoute
  '/admin/_prive/journal-audit': typeof AdminPriveJournalAuditRoute
  '/admin/_prive/messages': typeof AdminPriveMessagesRoute
  '/admin/_prive/paiements': typeof AdminPrivePaiementsRoute
  '/admin/_prive/tableau-de-bord': typeof AdminPriveTableauDeBordRoute
  '/admin/_prive/utilisateurs': typeof AdminPriveUtilisateursRoute
  '/joueur/defis/$defiId': typeof JoueurDefisDefiIdRoute
  '/joueur/defis/nouveau': typeof JoueurDefisNouveauRoute
  '/joueur/matchs/$matchId': typeof JoueurMatchsMatchIdRoute
  '/joueur/defis/': typeof JoueurDefisIndexRoute
  '/joueur/matchs/': typeof JoueurMatchsIndexRoute
  '/admin/_prive/litiges/$litigeId': typeof AdminPriveLitigesLitigeIdRoute
  '/admin/_prive/matchs/$matchId': typeof AdminPriveMatchsMatchIdRoute
  '/api/matchs/$matchId/preuves': typeof ApiMatchsMatchIdPreuvesRoute
  '/api/preuves/$preuveId/fichier': typeof ApiPreuvesPreuveIdFichierRoute
  '/admin/_prive/litiges/': typeof AdminPriveLitigesIndexRoute
  '/admin/_prive/matchs/': typeof AdminPriveMatchsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/joueur'
    | '/sitemap.xml'
    | '/aide'
    | '/cgu'
    | '/comment-ca-marche'
    | '/confidentialite'
    | '/connexion'
    | '/defis'
    | '/inscription'
    | '/jeux'
    | '/mentions-legales'
    | '/mot-de-passe-oublie'
    | '/reinitialisation-mot-de-passe'
    | '/admin'
    | '/admin/connexion'
    | '/joueur/litiges'
    | '/joueur/notifications'
    | '/joueur/portefeuille'
    | '/joueur/profil'
    | '/joueur/tableau-de-bord'
    | '/admin/configurations'
    | '/admin/jeux-plateformes'
    | '/admin/journal-audit'
    | '/admin/messages'
    | '/admin/paiements'
    | '/admin/tableau-de-bord'
    | '/admin/utilisateurs'
    | '/joueur/defis/$defiId'
    | '/joueur/defis/nouveau'
    | '/joueur/matchs/$matchId'
    | '/joueur/defis/'
    | '/joueur/matchs/'
    | '/admin/litiges/$litigeId'
    | '/admin/matchs/$matchId'
    | '/api/matchs/$matchId/preuves'
    | '/api/preuves/$preuveId/fichier'
    | '/admin/litiges/'
    | '/admin/matchs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/joueur'
    | '/sitemap.xml'
    | '/aide'
    | '/cgu'
    | '/comment-ca-marche'
    | '/confidentialite'
    | '/connexion'
    | '/defis'
    | '/inscription'
    | '/jeux'
    | '/mentions-legales'
    | '/mot-de-passe-oublie'
    | '/reinitialisation-mot-de-passe'
    | '/admin'
    | '/admin/connexion'
    | '/joueur/litiges'
    | '/joueur/notifications'
    | '/joueur/portefeuille'
    | '/joueur/profil'
    | '/joueur/tableau-de-bord'
    | '/'
    | '/admin/configurations'
    | '/admin/jeux-plateformes'
    | '/admin/journal-audit'
    | '/admin/messages'
    | '/admin/paiements'
    | '/admin/tableau-de-bord'
    | '/admin/utilisateurs'
    | '/joueur/defis/$defiId'
    | '/joueur/defis/nouveau'
    | '/joueur/matchs/$matchId'
    | '/joueur/defis'
    | '/joueur/matchs'
    | '/admin/litiges/$litigeId'
    | '/admin/matchs/$matchId'
    | '/api/matchs/$matchId/preuves'
    | '/api/preuves/$preuveId/fichier'
    | '/admin/litiges'
    | '/admin/matchs'
  id:
    | '__root__'
    | '/_public'
    | '/joueur'
    | '/sitemap.xml'
    | '/_public/aide'
    | '/_public/cgu'
    | '/_public/comment-ca-marche'
    | '/_public/confidentialite'
    | '/_public/connexion'
    | '/_public/defis'
    | '/_public/inscription'
    | '/_public/jeux'
    | '/_public/mentions-legales'
    | '/_public/mot-de-passe-oublie'
    | '/_public/reinitialisation-mot-de-passe'
    | '/admin/_prive'
    | '/admin/connexion'
    | '/joueur/litiges'
    | '/joueur/notifications'
    | '/joueur/portefeuille'
    | '/joueur/profil'
    | '/joueur/tableau-de-bord'
    | '/_public/'
    | '/admin/_prive/configurations'
    | '/admin/_prive/jeux-plateformes'
    | '/admin/_prive/journal-audit'
    | '/admin/_prive/messages'
    | '/admin/_prive/paiements'
    | '/admin/_prive/tableau-de-bord'
    | '/admin/_prive/utilisateurs'
    | '/joueur/defis/$defiId'
    | '/joueur/defis/nouveau'
    | '/joueur/matchs/$matchId'
    | '/joueur/defis/'
    | '/joueur/matchs/'
    | '/admin/_prive/litiges/$litigeId'
    | '/admin/_prive/matchs/$matchId'
    | '/api/matchs/$matchId/preuves'
    | '/api/preuves/$preuveId/fichier'
    | '/admin/_prive/litiges/'
    | '/admin/_prive/matchs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  JoueurRoute: typeof JoueurRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminPriveRoute: typeof AdminPriveRouteWithChildren
  AdminConnexionRoute: typeof AdminConnexionRoute
  ApiMatchsMatchIdPreuvesRoute: typeof ApiMatchsMatchIdPreuvesRoute
  ApiPreuvesPreuveIdFichierRoute: typeof ApiPreuvesPreuveIdFichierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joueur': {
      id: '/joueur'
      path: '/joueur'
      fullPath: '/joueur'
      preLoaderRoute: typeof JoueurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/aide': {
      id: '/_public/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof PublicAideRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cgu': {
      id: '/_public/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof PublicCguRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/comment-ca-marche': {
      id: '/_public/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof PublicCommentCaMarcheRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/confidentialite': {
      id: '/_public/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof PublicConfidentialiteRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/connexion': {
      id: '/_public/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof PublicConnexionRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/defis': {
      id: '/_public/defis'
      path: '/defis'
      fullPath: '/defis'
      preLoaderRoute: typeof PublicDefisRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/inscription': {
      id: '/_public/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof PublicInscriptionRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/jeux': {
      id: '/_public/jeux'
      path: '/jeux'
      fullPath: '/jeux'
      preLoaderRoute: typeof PublicJeuxRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/mentions-legales': {
      id: '/_public/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof PublicMentionsLegalesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/mot-de-passe-oublie': {
      id: '/_public/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof PublicMotDePasseOublieRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reinitialisation-mot-de-passe': {
      id: '/_public/reinitialisation-mot-de-passe'
      path: '/reinitialisation-mot-de-passe'
      fullPath: '/reinitialisation-mot-de-passe'
      preLoaderRoute: typeof PublicReinitialisationMotDePasseRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/_prive': {
      id: '/admin/_prive'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminPriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/connexion': {
      id: '/admin/connexion'
      path: '/admin/connexion'
      fullPath: '/admin/connexion'
      preLoaderRoute: typeof AdminConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joueur/litiges': {
      id: '/joueur/litiges'
      path: '/litiges'
      fullPath: '/joueur/litiges'
      preLoaderRoute: typeof JoueurLitigesRouteImport
      parentRoute: typeof JoueurRoute
    }
    '/joueur/notifications': {
      id: '/joueur/notifications'
      path: '/notifications'
      fullPath: '/joueur/notifications'
      preLoaderRoute: typeof JoueurNotificationsRouteImport
      parentRoute: typeof JoueurRoute
    }
    '/joueur/portefeuille': {
      id: '/joueur/portefeuille'
      path: '/portefeuille'
      fullPath: '/joueur/portefeuille'
      preLoaderRoute: typeof JoueurPortefeuilleRouteImport
      parentRoute: typeof JoueurRoute
    }
    '/joueur/profil': {
      id: '/joueur/profil'
      path: '/profil'
      fullPath: '/joueur/profil'
      preLoaderRoute: typeof JoueurProfilRouteImport
      parentRoute: typeof JoueurRoute
    }
    '/joueur/tableau-de-bord': {
      id: '/joueur/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/joueur/tableau-de-bord'
      preLoaderRoute: typeof JoueurTableauDeBordRouteImport
      parentRoute: typeof JoueurRoute
    }
    '/admin/_prive/configurations': {
      id: '/admin/_prive/configurations'
      path: '/configurations'
      fullPath: '/admin/configurations'
      preLoaderRoute: typeof AdminPriveConfigurationsRouteImport
      parentRoute: typeof AdminPriveRoute
    }
    '/admin/_prive/jeux-plateformes': {
      id: '/admin/_prive/jeux-plateformes'
      path: '/jeux-plateformes'
      fullPath: '/admin/jeux-plateformes'
      preLoaderRoute: typeof AdminPriveJeuxPlateformesRouteImport
      parentRoute: typeof AdminPriveRoute
    }
    '/admin/_prive/journal-audit': {
      id: '/admin/_prive/journal-audit'
      path: '/journal-audit'
      fullPath: '/admin/journal-audit'
      preLoaderRoute: typeof AdminPriveJournalAuditRouteImport
      parentRoute: typeof AdminPriveRoute
    }
    '/admin/_prive/messages': {
      id: '/admin/_prive/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminPriveMessagesRouteImport
      parentRoute: typeof AdminPriveRoute
    }
    '/admin/_prive/paiements': {
      id: '/admin/_prive/paiements'
      path: '/paiements'
      fullPath: '/admin/paiements'
      preLoaderRoute: typeof AdminPrivePaiementsRouteImport
      parentRoute: typeof AdminPriveRoute
    }
    '/admin/_prive/tableau-de-bord': {
      id: '/admin/_prive/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/admin/tableau-de-bord'
      preLoaderRoute: typeof AdminPriveTableauDeBordRouteImport
      parentRoute: typeof AdminPriveRoute
    }
    '/admin/_prive/utilisateurs': {
      id: '/admin/_prive/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AdminPriveUtilisateursRouteImport
      parentRoute: typeof AdminPriveRoute
    }
    '/joueur/defis/': {
      id: '/joueur/defis/'
      path: '/defis'
      fullPath: '/joueur/defis/'
      preLoaderRoute: typeof JoueurDefisIndexRouteImport
      parentRoute: typeof JoueurRoute
    }
    '/joueur/defis/$defiId': {
      id: '/joueur/defis/$defiId'
      path: '/defis/$defiId'
      fullPath: '/joueur/defis/$defiId'
      preLoaderRoute: typeof JoueurDefisDefiIdRouteImport
      parentRoute: typeof JoueurRoute
    }
    '/joueur/defis/nouveau': {
      id: '/joueur/defis/nouveau'
      path: '/defis/nouveau'
      fullPath: '/joueur/defis/nouveau'
      preLoaderRoute: typeof JoueurDefisNouveauRouteImport
      parentRoute: typeof JoueurRoute
    }
    '/joueur/matchs/': {
      id: '/joueur/matchs/'
      path: '/matchs'
      fullPath: '/joueur/matchs/'
      preLoaderRoute: typeof JoueurMatchsIndexRouteImport
      parentRoute: typeof JoueurRoute
    }
    '/joueur/matchs/$matchId': {
      id: '/joueur/matchs/$matchId'
      path: '/matchs/$matchId'
      fullPath: '/joueur/matchs/$matchId'
      preLoaderRoute: typeof JoueurMatchsMatchIdRouteImport
      parentRoute: typeof JoueurRoute
    }
    '/admin/_prive/litiges/': {
      id: '/admin/_prive/litiges/'
      path: '/litiges'
      fullPath: '/admin/litiges/'
      preLoaderRoute: typeof AdminPriveLitigesIndexRouteImport
      parentRoute: typeof AdminPriveRoute
    }
    '/admin/_prive/litiges/$litigeId': {
      id: '/admin/_prive/litiges/$litigeId'
      path: '/litiges/$litigeId'
      fullPath: '/admin/litiges/$litigeId'
      preLoaderRoute: typeof AdminPriveLitigesLitigeIdRouteImport
      parentRoute: typeof AdminPriveRoute
    }
    '/admin/_prive/matchs/': {
      id: '/admin/_prive/matchs/'
      path: '/matchs'
      fullPath: '/admin/matchs/'
      preLoaderRoute: typeof AdminPriveMatchsIndexRouteImport
      parentRoute: typeof AdminPriveRoute
    }
    '/admin/_prive/matchs/$matchId': {
      id: '/admin/_prive/matchs/$matchId'
      path: '/matchs/$matchId'
      fullPath: '/admin/matchs/$matchId'
      preLoaderRoute: typeof AdminPriveMatchsMatchIdRouteImport
      parentRoute: typeof AdminPriveRoute
    }
    '/api/matchs/$matchId/preuves': {
      id: '/api/matchs/$matchId/preuves'
      path: '/api/matchs/$matchId/preuves'
      fullPath: '/api/matchs/$matchId/preuves'
      preLoaderRoute: typeof ApiMatchsMatchIdPreuvesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preuves/$preuveId/fichier': {
      id: '/api/preuves/$preuveId/fichier'
      path: '/api/preuves/$preuveId/fichier'
      fullPath: '/api/preuves/$preuveId/fichier'
      preLoaderRoute: typeof ApiPreuvesPreuveIdFichierRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PublicRouteChildren {
  PublicAideRoute: typeof PublicAideRoute
  PublicCguRoute: typeof PublicCguRoute
  PublicCommentCaMarcheRoute: typeof PublicCommentCaMarcheRoute
  PublicConfidentialiteRoute: typeof PublicConfidentialiteRoute
  PublicConnexionRoute: typeof PublicConnexionRoute
  PublicDefisRoute: typeof PublicDefisRoute
  PublicInscriptionRoute: typeof PublicInscriptionRoute
  PublicJeuxRoute: typeof PublicJeuxRoute
  PublicMentionsLegalesRoute: typeof PublicMentionsLegalesRoute
  PublicMotDePasseOublieRoute: typeof PublicMotDePasseOublieRoute
  PublicReinitialisationMotDePasseRoute: typeof PublicReinitialisationMotDePasseRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAideRoute: PublicAideRoute,
  PublicCguRoute: PublicCguRoute,
  PublicCommentCaMarcheRoute: PublicCommentCaMarcheRoute,
  PublicConfidentialiteRoute: PublicConfidentialiteRoute,
  PublicConnexionRoute: PublicConnexionRoute,
  PublicDefisRoute: PublicDefisRoute,
  PublicInscriptionRoute: PublicInscriptionRoute,
  PublicJeuxRoute: PublicJeuxRoute,
  PublicMentionsLegalesRoute: PublicMentionsLegalesRoute,
  PublicMotDePasseOublieRoute: PublicMotDePasseOublieRoute,
  PublicReinitialisationMotDePasseRoute: PublicReinitialisationMotDePasseRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface JoueurRouteChildren {
  JoueurLitigesRoute: typeof JoueurLitigesRoute
  JoueurNotificationsRoute: typeof JoueurNotificationsRoute
  JoueurPortefeuilleRoute: typeof JoueurPortefeuilleRoute
  JoueurProfilRoute: typeof JoueurProfilRoute
  JoueurTableauDeBordRoute: typeof JoueurTableauDeBordRoute
  JoueurDefisDefiIdRoute: typeof JoueurDefisDefiIdRoute
  JoueurDefisNouveauRoute: typeof JoueurDefisNouveauRoute
  JoueurMatchsMatchIdRoute: typeof JoueurMatchsMatchIdRoute
  JoueurDefisIndexRoute: typeof JoueurDefisIndexRoute
  JoueurMatchsIndexRoute: typeof JoueurMatchsIndexRoute
}

const JoueurRouteChildren: JoueurRouteChildren = {
  JoueurLitigesRoute: JoueurLitigesRoute,
  JoueurNotificationsRoute: JoueurNotificationsRoute,
  JoueurPortefeuilleRoute: JoueurPortefeuilleRoute,
  JoueurProfilRoute: JoueurProfilRoute,
  JoueurTableauDeBordRoute: JoueurTableauDeBordRoute,
  JoueurDefisDefiIdRoute: JoueurDefisDefiIdRoute,
  JoueurDefisNouveauRoute: JoueurDefisNouveauRoute,
  JoueurMatchsMatchIdRoute: JoueurMatchsMatchIdRoute,
  JoueurDefisIndexRoute: JoueurDefisIndexRoute,
  JoueurMatchsIndexRoute: JoueurMatchsIndexRoute,
}

const JoueurRouteWithChildren =
  JoueurRoute._addFileChildren(JoueurRouteChildren)

interface AdminPriveRouteChildren {
  AdminPriveConfigurationsRoute: typeof AdminPriveConfigurationsRoute
  AdminPriveJeuxPlateformesRoute: typeof AdminPriveJeuxPlateformesRoute
  AdminPriveJournalAuditRoute: typeof AdminPriveJournalAuditRoute
  AdminPriveMessagesRoute: typeof AdminPriveMessagesRoute
  AdminPrivePaiementsRoute: typeof AdminPrivePaiementsRoute
  AdminPriveTableauDeBordRoute: typeof AdminPriveTableauDeBordRoute
  AdminPriveUtilisateursRoute: typeof AdminPriveUtilisateursRoute
  AdminPriveLitigesLitigeIdRoute: typeof AdminPriveLitigesLitigeIdRoute
  AdminPriveMatchsMatchIdRoute: typeof AdminPriveMatchsMatchIdRoute
  AdminPriveLitigesIndexRoute: typeof AdminPriveLitigesIndexRoute
  AdminPriveMatchsIndexRoute: typeof AdminPriveMatchsIndexRoute
}

const AdminPriveRouteChildren: AdminPriveRouteChildren = {
  AdminPriveConfigurationsRoute: AdminPriveConfigurationsRoute,
  AdminPriveJeuxPlateformesRoute: AdminPriveJeuxPlateformesRoute,
  AdminPriveJournalAuditRoute: AdminPriveJournalAuditRoute,
  AdminPriveMessagesRoute: AdminPriveMessagesRoute,
  AdminPrivePaiementsRoute: AdminPrivePaiementsRoute,
  AdminPriveTableauDeBordRoute: AdminPriveTableauDeBordRoute,
  AdminPriveUtilisateursRoute: AdminPriveUtilisateursRoute,
  AdminPriveLitigesLitigeIdRoute: AdminPriveLitigesLitigeIdRoute,
  AdminPriveMatchsMatchIdRoute: AdminPriveMatchsMatchIdRoute,
  AdminPriveLitigesIndexRoute: AdminPriveLitigesIndexRoute,
  AdminPriveMatchsIndexRoute: AdminPriveMatchsIndexRoute,
}

const AdminPriveRouteWithChildren = AdminPriveRoute._addFileChildren(
  AdminPriveRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  JoueurRoute: JoueurRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminPriveRoute: AdminPriveRouteWithChildren,
  AdminConnexionRoute: AdminConnexionRoute,
  ApiMatchsMatchIdPreuvesRoute: ApiMatchsMatchIdPreuvesRoute,
  ApiPreuvesPreuveIdFichierRoute: ApiPreuvesPreuveIdFichierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
